language: ruby
cache: bundler
rvm:
  - &latest_ruby 2.7.0
  - 2.4
env:
  - JEKYLL_VERSION="~> 3.8"
matrix:
  include:
    - # GitHub Pages
      rvm: 2.5.3
      env: GH_PAGES=true
    - rvm: *latest_ruby
      env: JEKYLL_VERSION="~> 4.0"

before_install:
  - gem update --system
  - gem install bundler
before_script: bundle update
script: script/cibuild
branches:
  only:
    - master
notifications:
  irc:
    on_success: change
    on_failure: change
    channels:
    - irc.freenode.org#jekyll
    template:
    - '%{repository}#%{build_number} (%{branch}) %{message} %{build_url}'
  email:
    on_success: never
    on_failure: never
